server:
  port: 80

# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: t
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 28800
  # 非并发登录
  is-concurrent: false
  # token风格
  token-style: simple-uuid

spring:
  # 数据库配置
  datasource:
    # 连接地址
    url: jdbc:mysql://127.0.0.1:3306/one_piece?useUnicode=true&characterEncoding=UTF-8
    # 用户名
    username: root
    # 测试库密码
    password: 123456
    # 驱动地址
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接配置
    tomcat:
      # 最大空闲连接数
      max-idle: 5
      # 最大连接数
      max-active: 10
  # 配置可上传文件的最大容量
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # Freemarker配置
  freemarker:
    # 关闭缓存，及时进行刷新，上线生产环境，需要改成 true
    cache: false
    # 设置编码的样式
    charset: UTF-8
    #是否检查模板的位置
    check-template-location: false
    # 模板的样式
    content-type: text/html
    # 是否曝露
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    # 后缀
    suffix: .html
  # 格式化后台返回日期格式
  jackson:
    date-format: yyyy-MM-dd

# 指定log4j2配置文件
logging:
  config: classpath:log4j2/log4j2-spring.xml

# MyBatis-Plus配置项
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
  type-aliases-package: com.kiwi.pojo.po
  mapper-locations: classpath:mapper/*.xml

# 图片服务器所在IP
photo:
  photo_url: "http://47.117.0.159:8080/image/"
  photo_path: "/usr/local/image/"